title: "Predicting direction of stock price from interest rate and inflation rate"
author: "Allan Lee, Jianhao Zhang, Yi Yan, Chengyu Tao"
date: "2023-12-02"
sphinx:
  config:
    bibtex_reference_style: author_year
execute:
  execute_notebooks: force
bibtex_bibfiles:
  - references.bib
