# Install the project conda environment by running 
# the following command in your conda base environment:
# conda env create -f environment.yaml
name: '522'
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.*
  - pip
  - ipykernel
  - nb_conda_kernels
  - altair=5.1.2
  - vl-convert-python  # For saving altair charts as static images
  - vegafusion  # For working with charts > 5,000 graphical objects
  - vegafusion-python-embed  # Same as the previous one
  - vegafusion-jupyter  # For working with charts > 100,000 graphical objects
  - vega_datasets  # Altair example data
  - scipy
  - matplotlib>=3.2.2
  - scikit-learn>=1.3.1
  - requests>=2.24.0
  - graphviz
  - python-graphviz
  - eli5
  - shap
  - jinja2
  - selenium<4.3.0
  - lightgbm
  - pip:
    - joblib==1.1.0
    - mglearn
    - psutil>=5.7.2
